plugins {
    id 'gg.essential.multi-version'
    id 'gg.essential.defaults'
    id 'java-library'
}

dependencies {
    def fabricApiVersion
    if (platform.mcVersion == 12001) {
        fabricApiVersion = "0.92.2+1.20.1"
    } else if (platform.mcVersion == 12101) {
        fabricApiVersion = "0.110.0+1.21.1"
    } else if (platform.mcVersion == 12104) {
        fabricApiVersion = "0.111.0+1.21.4"
    } else if (platform.mcVersion == 12105) {
        fabricApiVersion = "0.119.6+1.21.5"
    } else if (platform.mcVersion == 12108) {
        fabricApiVersion = "0.131.0+1.21.8"
    } else if (platform.mcVersion == 12111) {
        fabricApiVersion = "0.139.5+1.21.11";
    } else if (platform.mcVersion == 260102) {
        fabricApiVersion = "0.146.1+26.1.2"
    } else if (platform.mcVersion == 260200) {
        fabricApiVersion = "0.154.0+26.2"
    } else {
        throw org.gradle.api.GradleException("Unsupported platform $platform")
    }

    if (platform.isUnobfuscated) {
        compileOnly "net.fabricmc.fabric-api:fabric-api:$fabricApiVersion"
        compileOnly 'org.projectlombok:lombok:1.18.38'
    } else {
        modCompileOnly "net.fabricmc.fabric-api:fabric-api:$fabricApiVersion"
        modCompileOnly 'org.projectlombok:lombok:1.18.38'
    }


    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    shadow project(path: ':common')
}

jar.enabled = false
assemble.dependsOn shadowJar
shadowJar {
    configurations = [project.configurations.shadow]
    if (!platform.isUnobfuscated) {
        destinationDirectory.set(file("$projectDir/build/libs"))
    } else {
        destinationDirectory.set(file("$rootDir/target/"))
        archiveClassifier.set('')
    }

    exclude('net.fabricmc:.*')
    exclude('net.kyori:.*')
    exclude '/mappings/*'
}

if (!platform.isUnobfuscated) {
    remapJar {
        dependsOn tasks.shadowJar
        mustRunAfter tasks.shadowJar
        inputFile = shadowJar.archiveFile.get()
        addNestedDependencies = true

        destinationDirectory.set(file("$rootDir/target/"))
        archiveClassifier.set('')
    }

    shadowJar.finalizedBy(remapJar)
}