plugins {
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    minecraft "com.mojang:minecraft:26.1.2"

    implementation 'net.fabricmc:fabric-loader:0.19.2'
    implementation 'net.fabricmc.fabric-api:fabric-api:0.146.1+26.1.2'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    shadow project(path: ':common')
}

sourceSets {
    main {
        java.srcDirs = ['../src/main/java']
        resources.srcDirs = ['../src/main/resources']
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

shadowJar {
    configurations = [project.configurations.shadow]
    destinationDirectory.set(file("$projectDir/build/libs"))
    archiveClassifier.set('')

    exclude('net.fabricmc:.*')
    exclude('net.kyori:.*')
    exclude '/mappings/*'
}
